# Environment variables
env:
  GIT_USER_EMAIL: "security@escapace.com"
  GIT_USER_NAME: "esceapace"
  GIT_USER_SIGNINGKEY: "0xF29CCEBC83FD4525"
  DOCKER_SCOPE: "escapace"
  PACKER_VERSION: "1.4.3"
  RESTIC_VERSION: "0.9.4"
  TERRAFORM_VERSION: "0.11.13"

# Enable manage repository scripts
enable:
  - help
  - trust-escapace

# Default script
default: help
