directories:
  script: scripts
  module: scripts/modules

# Environment variables
env:
  TERRAFORM_BINARY: "https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip"
  TERRAFORM_SHA256SUMS: "https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_SHA256SUMS"
  TERRAFORM_SHA256SUMS_SIGNATURE: "https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_SHA256SUMS.sig"
  DOCKER_SCOPE: "testing"

# Enable manage repository scripts
enable:
  - help

# Default script
default: help
