#!/usr/bin/env bash
# @description install requirements
# @import lang/exists
# @import console/die
# @import console/info

main ()
{
    _ exists ansible || {
        _ exists pip || _ die 'command not found: pip'
        pip install -r "${MANAGE_REPOSITORY}/requirements.txt"
    }
}
