#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# @description Run packer configuration test(s)
# @import stack/stackTerraform
# @import lang/required
# @dependency jq

main ()
{
    verbose true
    strict true

    local module="$1"

    _ stackTerraform "${module}"
}
