#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# @description Build and destroy packer images
# @import github.com/escapace/stack-tools stack/stackPacker
# @import lang/required
# @dependency jq

main ()
{
    verbose true
    strict true

    local template="$1"
    local type="$2"

    _ stackPacker "${template}" "${type}"
}
