#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# @import console/info
# @import console/die
# @import path/relativePath
# @import path/absolutePath
# @import lang/required
# @import github.com/escapace/stack-tools stack/stackValidate
# @description Validate configurations

main () {
    verbose true
    strict true

    local code=0

    if _ required "$1"
    then
        _ stackValidate  "$(_ absolutePath "${1}")" || (( ++code ))
    else
        while read -d '' -r directory
        do
            _ stackValidate "${directory}" || (( ++code ))
        done < <(find "${MANAGE_REPOSITORY}/terraform" -mindepth 2 -maxdepth 2 -type d ! -path "*.terraform*" -print0 2> /dev/null)
    fi

    if (( code != 0 ))
    then
        return 1
    fi
}
